apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-config
  labels:
    app: rocketmq-service
data:
  config: |
    brokerClusterName = DefaultCluster
    brokerName = broker-a
    brokerId = 0
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = SYNC_FLUSH
    brokerIp1 = # todo 指定brokerIp地址
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-server-log-pv
  labels:
    app: rocketmq-service-log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/dev/rocketmq/logs
    server: nfs.server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-server-log-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: rocketmq-service-log
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-server-store-pv
  labels:
    app: rocketmq-service-store
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/dev/rocketmq/store
    server: nfs.server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-server-store-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: rocketmq-service-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: rocketmq-service
  name: rocketmq-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-service
  template:
    metadata:
      labels:
        app: rocketmq-service
    spec:
      containers:
      - command:
        - sh
        - mqbroker
        - -c
        - /opt/rocketmq-4.3.2/conf/broker.properties
        - -n
        - localhost:9876
        image: rocketmqinc/rocketmq:4.3.2
        imagePullPolicy: Always
        env: 
        - name: MAX_POSSIBLE_HEAP
          value: "1073741824"
        name: broker
        ports:
        - containerPort: 10909
          protocol: TCP
          hostPort: 10909
        - containerPort: 10911
          protocol: TCP
          hostPort: 10911
        resources: 
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /opt/rocketmq-4.3.2/conf/broker.properties
          name: configmap
          subPath: broker.properties
        - name: store-data
          mountPath: /home/rocketmq/store
        - name: log-data
          mountPath: /home/rocketmq/logs/rocketmqlogs
      - command:
        - sh
        - mqnamesrv
        image: rocketmqinc/rocketmq:4.3.2
        imagePullPolicy: IfNotPresent
        env:
        - name: MAX_POSSIBLE_HEAP
          value: "134217728"
        name: namesrv
        ports:
        - containerPort: 9876
          hostPort: 9876
          protocol: TCP
        resources: 
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          privileged: true
      restartPolicy: Always  
      volumes:
      - configMap:
          items:
          - key: config
            path: broker.properties
          name: rocketmq-config
        name: configmap
      - name: log-data
        persistentVolumeClaim:
          claimName: rocketmq-server-log-pvc
      - name: store-data
        persistentVolumeClaim:
          claimName: rocketmq-server-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocketmq-service
  name: rocketmq-service
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
    name: port1
  - port: 10909
    protocol: TCP
    targetPort: 10909
    name: port2
  - port: 10911
    protocol: TCP
    targetPort: 10911
    name: port3
  selector:
    app: rocketmq-service
  type: ClusterIP