apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxljob-server
spec:
  selector:
    matchLabels:
      app: xxljob-server
  template:
    metadata:
      labels:
        app: xxljob-server
    spec:
      containers:
      - name: xxljob-server
        image: xuxueli/xxl-job-admin:2.2.0
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://mysql-server:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=654321"
---
apiVersion: v1
kind: Service
metadata:
  name: xxljob-server
  labels:
    app: xxljob-server
spec:
  type: NodePort
  selector:
    app: xxljob-server
  ports:
  - name: server
    port: 8080
    targetPort: 8080
    nodePort: 32003

