apiVersion: v1
kind: Service
metadata:
  name: nacos-server
  labels:
    app: nacos-server
spec:
  type: NodePort
  ports:
    - name: server       
      port: 8848
      targetPort: 8848
      nodePort: 33848
  selector:
    app: nacos-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-server
  labels:
    app: nacos-server
spec:
  replicas: 1              
  selector:
    matchLabels:
      app: nacos-server
  template:
    metadata:
      labels:
        app: nacos-server
    spec:
      containers:
      - name: nacos-server
        image: nacos/nacos-server:1.3.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8848
          name: server
        env:
        - name: MODE
          value: "standalone"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          value: "mysql"
        - name: MYSQL_SERVICE_PORT
          value: "3306"    
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_USER
          value: "root"
        - name: MYSQL_SERVICE_PASSWORD
          value: "123456"               
        - name: JVM_XMS
          value: "1024m"
        - name: JVM_XMX
          value: "1024m"
        - name: JVM_XMN
          value: "512m"
        resources: 
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
