kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-server-pvc
spec:
  resources:
    requests:
      storage: 50G
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: mysql-server-pv
