apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: my-namespace
  labels:
    app: mysql-server
spec:
  type: NodePort
  ports:
    - name: server
      port: 3306
      targetPort: 3306
      nodePort: 32000
  selector:
    app: mysql-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: my-namespace
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels: 
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:8.0.25
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/
        ports:
        - containerPort: 3306
          name: server
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "654321"
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 4000m
            memory: 8Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-server-pvc
      - name: config
        configMap:
          name: mysql-server-config
