apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-server-config
  namespace: micro-system-app
data:
  my.cnf: |-
    [mysqld]
    port = 3306
    max_connections                 =5000
    max_connect_errors              =100000
    max_user_connections            =1200
    max_execution_time              =10000
    group_concat_max_len            =1048576
    lock_wait_timeout               =60
    read_buffer_size                =1M
    read_rnd_buffer_size            =2M
    sort_buffer_size                =1M
    join_buffer_size                =1M
    tmp_table_size                  =64M
    max_allowed_packet              =64M
    max_heap_table_size             =64M
    connect_timeout                 =10
    wait_timeout                    =600
    interactive_timeout             =28800
    net_read_timeout                =30
    net_write_timeout               =30
    secure_file_priv                =/var/lib/mysql

