kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-server-config
  labels:
    app: redis-server
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    pidfile /data/redis-6379.pid
    maxmemory 2147483648
    requirepass redis
