apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-server-pv
  labels:
    app: redis-server
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: xxx
    path: /nfs/dev/redis
  persistentVolumeReclaimPolicy: Retain

